package org.example;// Generated by Selenium IDE

import static org.assertj.core.api.Assertions.assertThat;

import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;


@ExtendWith(SeleniumJupiter.class)
class AppTest {
  private final WebDriver driver;
  private static final String BLAZE_URL = "https://blazedemo.com/";

  public AppTest(FirefoxDriver driver){
    this.driver = driver;
  }

  @Test
  public void testinho() {
    // Test name: Testinho
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://blazedemo.com/");
    // 2 | setWindowSize | 1680x1050 | 
    driver.manage().window().setSize(new Dimension(1680, 1050));
    // 3 | click | name=fromPort | 
    driver.findElement(By.name("fromPort")).click();
    // 4 | select | name=fromPort | label=Philadelphia
    {
      WebElement dropdown = driver.findElement(By.name("fromPort"));
      dropdown.findElement(By.xpath("//option[. = 'Philadelphia']")).click();
    }
    // 5 | click | css=.form-inline:nth-child(1) > option:nth-child(2) | 
    driver.findElement(By.cssSelector(".form-inline:nth-child(1) > option:nth-child(2)")).click();
    // 6 | click | name=toPort | 
    driver.findElement(By.name("toPort")).click();
    // 7 | select | name=toPort | label=London
    {
      WebElement dropdown = driver.findElement(By.name("toPort"));
      dropdown.findElement(By.xpath("//option[. = 'London']")).click();
    }
    // 8 | click | css=.form-inline:nth-child(4) > option:nth-child(3) | 
    driver.findElement(By.cssSelector(".form-inline:nth-child(4) > option:nth-child(3)")).click();
    // 9 | click | css=.btn-primary | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
    // 10 | click | css=tr:nth-child(2) .btn | 
    driver.findElement(By.cssSelector("tr:nth-child(2) .btn")).click();
    // 11 | type | id=inputName | Sou
    driver.findElement(By.id("inputName")).sendKeys("Sou");
    // 12 | click | id=address | 
    driver.findElement(By.id("address")).click();
    // 13 | type | id=address | 123 coisa
    driver.findElement(By.id("address")).sendKeys("123 coisa");
    // 14 | click | id=city | 
    driver.findElement(By.id("city")).click();
    // 15 | type | id=city | wubba
    driver.findElement(By.id("city")).sendKeys("wubba");
    // 16 | click | id=state | 
    driver.findElement(By.id("state")).click();
    // 17 | type | id=state | lubba
    driver.findElement(By.id("state")).sendKeys("lubba");
    // 18 | click | id=zipCode | 
    driver.findElement(By.id("zipCode")).click();
    // 19 | type | id=zipCode | 9192
    driver.findElement(By.id("zipCode")).sendKeys("9192");
    // 20 | select | id=cardType | label=American Express
    {
      WebElement dropdown = driver.findElement(By.id("cardType"));
      dropdown.findElement(By.xpath("//option[. = 'American Express']")).click();
    }
    // 21 | click | css=option:nth-child(2) | 
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    // 22 | click | id=creditCardNumber | 
    driver.findElement(By.id("creditCardNumber")).click();
    // 23 | type | id=creditCardNumber | 9182
    driver.findElement(By.id("creditCardNumber")).sendKeys("9182");
    // 24 | click | id=creditCardMonth | 
    driver.findElement(By.id("creditCardMonth")).click();
    // 25 | type | id=creditCardMonth | 12
    driver.findElement(By.id("creditCardMonth")).sendKeys("12");
    // 26 | click | id=creditCardYear | 
    driver.findElement(By.id("creditCardYear")).click();
    // 27 | type | id=creditCardYear | 2022
    driver.findElement(By.id("creditCardYear")).sendKeys("2022");
    // 28 | click | id=nameOnCard | 
    driver.findElement(By.id("nameOnCard")).click();
    // 29 | type | id=nameOnCard | Mr G
    driver.findElement(By.id("nameOnCard")).sendKeys("Mr G");
    // 30 | click | css=.btn-primary | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
    // 31 | assertTitle | BlazeDemo Confirmation | 
    assertThat(driver.getTitle()).isEqualTo("BlazeDemo Confirmation");
  }
}
