package org.example.Tests;// Generated by Selenium IDE

import static org.assertj.core.api.Assertions.assertThat;

import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.How;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.Select;


@ExtendWith(SeleniumJupiter.class)
class AppTest {
    private final WebDriver driver;

    @FindBy(how = How.NAME, using = "fromPort")
    private WebElement fromPort;

    @FindBy(how = How.NAME, using = "toPort")
    private WebElement toPort;

    @FindBy(how = How.CLASS_NAME, using = "btn-primary")
    private WebElement btn_primary;

    @FindBy(id = "inputName")
    private WebElement nameInput;

    @FindBy(id = "address")
    private WebElement addressInput;

    @FindBy(id = "city")
    private WebElement cityInput;

    @FindBy(id = "state")
    private WebElement stateInput;

    @FindBy(id = "zipCode")
    private WebElement zipCodeInput;

    @FindBy(id = "cardType")
    private WebElement cardTypeDropdown;

    @FindBy(id = "creditCardNumber")
    private WebElement creditCardNumberInput;

    @FindBy(id = "creditCardMonth")
    private WebElement creditCardMonthInput;

    @FindBy(id = "creditCardYear")
    private WebElement creditCardYearInput;

    @FindBy(id = "nameOnCard")
    private WebElement nameOnCardInput;


    @FindBy(css = ".form-inline:nth-child(1) > option:nth-child(2)")
    private WebElement dropdownOptionFromPort;

    @FindBy(css = ".form-inline:nth-child(1) > option:nth-child(2)")
    private WebElement dropdownOptionToPort;

    @FindBy(css = "tr:nth-child(2) .btn")
    private WebElement dropdownOptionBtn;




    public AppTest(FirefoxDriver driver){
        this.driver = driver;
        driver.get("https://blazedemo.com/");
        //Initialise Elements
        PageFactory.initElements(driver, this);
    }

    @Test
    public void testinho() {
        // Test name: Testinho
        // Step # | name | target | value
        // 2 | setWindowSize | minimize |
        //driver.manage().window().minimize();
        // 3 | click | name=fromPort |
        clickFromPort();
        // 4 | select | name=fromPort | label=Philadelphia
        selectDropdownFromPort("Philadelphia");
        // 5 | click | css=.form-inline:nth-child(1) > option:nth-child(2) |
        clickDropdownFromPort();
        // 6 | click | name=toPort |
        clickToPort();
        // 7 | select | name=toPort | label=London
        selectDropdownToPort("London");
        // 8 | click | css=.form-inline:nth-child(4) > option:nth-child(3) |
        clickDropdownToPort();
        // 9 | click | css=.btn-primary |
        clickBtn_Primary();
        // 10 | click | css=tr:nth-child(2) .btn |
        clickBtn();
        // 11 | type | id=inputName | Sou
        fillForm("Sou", "123 coisa", "wubba", "lubba", "9192");
        // 20 | select | id=cardType | label=American Express
        selectCardType("American Express");
        enterCreditCardDetails("9182", "12", "2022", "Mr G");

        clickBtn_Primary();
        // 31 | assertTitle | BlazeDemo Confirmation |
        assertThat(getPageTitle()).isEqualTo("BlazeDemo Confirmation");
    }

    public void clickFromPort(){
        fromPort.click();
    }
    public void clickToPort(){
        toPort.click();
    }
    public void clickBtn_Primary(){
        btn_primary.click();
    }
    public void clickBtn(){
        dropdownOptionBtn.click();
    }

    public void selectDropdownFromPort(String option) {
        Select dropdown = new Select(fromPort);
        dropdown.selectByVisibleText(option);
    }

    public void selectDropdownToPort(String option) {
        Select dropdown = new Select(toPort);
        dropdown.selectByVisibleText(option);
    }

    public void clickDropdownFromPort() {
        dropdownOptionFromPort.click();
    }

    public void clickDropdownToPort() {
        dropdownOptionToPort.click();
    }

    public void fillForm(String name, String address, String city, String state, String zipCode) {
        nameInput.sendKeys(name);
        addressInput.sendKeys(address);
        cityInput.sendKeys(city);
        stateInput.sendKeys(state);
        zipCodeInput.sendKeys(zipCode);
    }

    public void selectCardType(String cardType) {
        cardTypeDropdown.click();
        WebElement option = cardTypeDropdown.findElement(By.xpath("//option[contains(text(), '" + cardType + "')]"));
        option.click();
    }
    public void enterCreditCardDetails(String cardNumber, String month, String year, String nameOnCard) {
        creditCardNumberInput.click();
        creditCardNumberInput.sendKeys(cardNumber);

        creditCardMonthInput.click();
        creditCardMonthInput.sendKeys(month);

        creditCardYearInput.click();
        creditCardYearInput.sendKeys(year);

        nameOnCardInput.click();
        nameOnCardInput.sendKeys(nameOnCard);
    }
    public String getPageTitle() {
        return driver.getTitle();
    }

}


