name: SonarQube

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Setup SonarQube
        uses: sonarsource/sonarqube-action@master
        with:
          sonar-host-url: '<SONARQUBE_URL>'
          sonar-login: '<SONARQUBE_LOGIN>'
          project-key: '<PROJECT_KEY>'
          project-name: '<PROJECT_NAME>'
          project-version: '1.0'
          sources: 'Hw1/Backend/src'
